name: CI

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  format_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Format and Lint
        uses: beauwilliams/run-node-formatter@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
