name: docker-cicd

on:
  push:
    branches:
      - main

env:  
  # We do not need Husky hooks installed for this workflow.
  HUSKY: 0

jobs:
  format_and_lint_and_test:
    name: Format, Lint, Test
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout the repo 
        uses: actions/checkout@v2
    
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "18.x"

      - name: Install dependencies
        run: npm install

      - name: Format Check
        run: npm run format-check
        
      - name: Lint
        run: npm run lint
        
      - name: Test
        run: npm run test

  build_and_push:
    name: Docker build and push
    needs: format_and_lint_and_test
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout the repo 
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build image 
        run: docker build -t nsgcr/netrunner-cards-json .
        
      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600
        
      - name: Tag image 
        run:
          docker tag nsgcr/netrunner-cards-json \
          registry.digitalocean.com/nsgcr/netrunner-cards-json:${{ github.run_id }}
          
      - name: Push image to DO Container Registry 
        run: docker push registry.digitalocean.com/nsgcr/netrunner-cards-json:${{ github.run_id }}
